# Generated by Django 4.2.1 on 2023-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finished",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
